//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaggageWeb.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_member()
        {
            this.tbl_orders = new HashSet<tbl_orders>();
        }
    
        public int C_id { get; set; }
        public string C_acc_username { get; set; }
        public string C_acc_userpass { get; set; }
        public Nullable<int> C_id_auth { get; set; }
        public Nullable<int> C_active { get; set; }
        public string C_email { get; set; }
    
        public virtual tbl_authorization tbl_authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_orders> tbl_orders { get; set; }
    }
}
