//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaggageWeb.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        public int o_id { get; set; }
        public Nullable<int> pro_id { get; set; }
        public Nullable<int> m_id { get; set; }
        public Nullable<System.DateTime> o_date { get; set; }
        public Nullable<int> o_status { get; set; }
        public Nullable<int> o_order_confirm { get; set; }
        public Nullable<int> o_price { get; set; }
    
        public virtual tbl_member tbl_member { get; set; }
        public virtual tbl_products tbl_products { get; set; }
    }
}
